name: go-carshop-backend

services:
  car-service:
    container_name: car-service
    build:
      context: ./car-service
    env_file:
      - ./car-service/.env
    image: car-service:local
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=car-service-db
      - REDIS_HOST=redis
    depends_on:
      car-service-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  car-service-db:
    image: postgres:18.1
    container_name: car-service-db
    environment:
      POSTGRES_USER: car_service_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_service
    ports:
      - "5432:5432"
    volumes:
      - car_service_postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U car_service_user -d car_service"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service-db:
    image: postgres:18.1
    container_name: order-service-db
    environment:
      POSTGRES_USER: order_service_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_service
    ports:
      - "5433:5432"
    volumes:
      - order_service_postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_service_user -d order_service"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0
    container_name: car-service-redis
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  car_service_postgres_data:
  order_service_postgres_data:
  redis_data:
  grafana_data:
