name: go-carshop-backend

services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_USER: car_service_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U car_service_user -d car_service"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data:
